### ISSUE TITLE
Creating new tasks doesn't prompt for parameters

### ISSUE THREAD

**Issue by hulto** [KCarretto/realm#295]
**Describe the bug**

**To Reproduce**
<img width="676" alt="image" src="https://github.com/KCarretto/realm/assets/7121375/9847f76a-82a7-489f-a1e7-4dca1ecca9b6">

**Expected behavior**
Should prompt for parameters based on the definitions.
_metadata.yml_
```yaml
name: Process list
description: Get a list of running processes
parameter_definitions:
  - name: cmd_substring
    type: string
```

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
